version: "3.5"

services:

  db-mysql:
    image: mysql:5.7
    container_name: "MySQL"
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "delivery"
    ports:
      - "3306:3306"
    networks: 
      default:
        ipv4_address: 10.0.0.3
    volumes:
      - ./mysql:/var/lib/mysql
              
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: "PHPMyAdmin"
    links:
      - db-mysql
    ports:
      - 7070:80
    networks: 
      default:
        ipv4_address: 10.0.0.4
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=3000000000


  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    hostname: rabbitmq
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './rabbitmq:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin 
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - network


networks: 
  network:
    driver: bridge
  default:
    ipam:
      config:
        - subnet: 10.0.0.0/16
        
