@baseUrl = http://localhost:4001
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTQ4NzIyOTgsInVzZXIiOjF9.hmb3JygVfxYW0HbtrL1xdcUZBbbnjTuLbQz42sZGDzY


### Cadastro 
POST {{baseUrl}}/user
Content-Type: application/json

{ 
	"name": "Tarcisio", 
	"email": "tarcisio.angelo@gmail.com",
    "password": "123456" 
}


### Login 
POST {{baseUrl}}/login
Content-Type: application/json

{ 
	"email": "tarcisio.angelo@gmail.com", 
    "password": "123456" 
}


### Listar
GET {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Atualizar 
PUT {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
	"name": "Tarcisio Angelo da Silva"
}


### Find
GET {{baseUrl}}/user/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### My Delete
DELETE {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

