@baseUrl = http://localhost:4001
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MTQ4NzgyOTcsInVzZXIiOjF9.ZVg5jCRNnfDUV8sDK6emjr1lc-nIe2vyhSipeuGiiqw


### Cadastro 
POST {{baseUrl}}/person/user
Content-Type: application/json

{ 
	"name": "Tarcisio", 
	"email": "tarcisio.angelo@gmail.com",
    "password": "123456" 
}


### Login 
POST {{baseUrl}}/person/login
Content-Type: application/json

{ 
	"email": "tarcisio.angelo@gmail.com", 
    "password": "123456" 
}


### Listar
GET {{baseUrl}}/person/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Atualizar 
PUT {{baseUrl}}/person/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{ 
	"name": "Tarcisio Angelo da Silva"
}


### Find
GET {{baseUrl}}/person/user/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### My Delete
DELETE {{baseUrl}}/person/user
Content-Type: application/json
Authorization: Bearer {{accessToken}}

